name: "Setup"
description: "Sets up environment"
runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.4
    - run: bun install
      shell: bash
