import { defineConfig } from "vite";
import path from "node:path";
import fs from "node:fs/promises";

const pathToServer = path.resolve(__dirname, "../../apps/server");
const pathToServerChecksum = path.resolve(pathToServer, "./src/checksum.ts");

export default defineConfig({
  build: {
    outDir: path.resolve(pathToServer, "./plugins"),
    emptyOutDir: false,
    rollupOptions: {
      output: {
        exports: "named",
      },
    },
    lib: {
      name: "flow-gitstart",
      entry: "src/server.ts",
      formats: ["cjs"],
      fileName: () => "gitstart.js",
    },
  },
  plugins: [
    {
      name: "change-server-checksum",
      buildEnd: async () => {
        await fs.writeFile(
          pathToServerChecksum,
          `/**
 * @generated
 * Do not change this file manually as it is automatically generated by plugins in developoment.
 * See plugins/gitstart/vite.server.dev.ts for example.
 */
export const checksum = "1694871724389";
`
        );
      },
    },
  ],
});
