/**
 * @generated
 * Do not change this file manually as it is automatically generated by plugins in developoment.
 * See plugins/gitstart/vite.server.dev.ts for example.
 */
export const checksum = "1694871724389";