export {};

declare global {
  // Linear Webhook types Generated by https://quicktype.io

  type LinearWebhookEvent = Partial<{
    action: string;
    createdAt: string;
    data?: Data;
    updatedFrom: UpdatedFrom;
    url: string;
    type: "Issue";
    organizationId: string;
  }>;

  type Data = Partial<{
    id: string;
    createdAt: string;
    updatedAt: string;
    number: number;
    title: string;
    priority: number;
    boardOrder: number;
    sortOrder: number;
    startedAt: string;
    teamId: string;
    cycleId: string;
    projectId: string;
    previousIdentifiers: any[];
    creatorId: string;
    assigneeId: string;
    stateId: string;
    priorityLabel: string;
    subscriberIds: string[];
    labelIds: any[];
    assignee?: Assignee;
    project?: Project;
    cycle: Cycle;
    state: State;
    team: Team;
  }>;

  type Assignee = Partial<{
    id: string;
    name: string;
  }>;

  type Project = Partial<{
    id: string;
    name: string;
  }>;

  type Cycle = Partial<{
    id: string;
    number: number;
    startsAt: string;
    endsAt: string;
  }>;

  type State = Partial<{
    id: string;
    name: string;
    color: string;
    type: string;
  }>;

  type Team = Partial<{
    id: string;
    name: string;
    key: string;
  }>;

  type UpdatedFrom = Partial<{
    updatedAt: string;
    sortOrder: number;
    startedAt: null;
    stateId: string;
  }>;
}
